name: ALPE-SHOP
main: EasyShop\Main
version: 0.0.1
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9]
author: Kirito
description: Buy And Sell Stuff With A GUI
commands:
 shop:
  description: Buy And Sell From ALPE SHOP
