name: Chalix-Shop-Aka-TheLazyGuysShopLOL
main: ChalixMC\Main
version: 0.0.1
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9]
author: Potatoe
description: Buy And Sell Stuff With A GUI
commands:
 shop:
  description: Opens The Shop GUI
